"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase/client";
import { Button } from "@/components/ui/button";
import {
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { AnimatedCard } from "@/components/ui/animated-card";
import { Mic, Video, FileText, LogOut, Upload, ScanSearch } from "lucide-react";

export default function DashboardPage() {
  const router = useRouter();
  const [userName, setUserName] = useState<string | null>(null);
  const [hasResume, setHasResume] = useState(false);
  const [language, setLanguage] = useState<string>("english");

  useEffect(() => {
    supabase.auth.getUser().then(({ data: { user } }) => {
      if (!user) { router.push("/login"); return; }

      // Name from Supabase metadata
      setUserName(user.user_metadata?.full_name ?? user.email ?? null);

      // Resume chunks and language live in localStorage (RAG)
      const chunks = localStorage.getItem("interview_chunks");
      const lang = localStorage.getItem("interview_language") || "english";
      setHasResume(!!chunks);
      setLanguage(lang);
    });
  }, [router]);

  const handleLogout = async () => {
    await supabase.auth.signOut();
    localStorage.removeItem("interview_chunks");
    localStorage.removeItem("interview_language");
    router.push("/");
  };

  const languageLabel: Record<string, string> = {
    english: "English · Voice",
    spanish: "Spanish · Voice",
    asl: "American Sign Language · Camera",
  };

  return (
    <div className="min-h-screen p-8">
      <div className="max-w-3xl mx-auto space-y-8">

        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold">
              Welcome{userName ? `, ${userName}` : ""}!
            </h1>
            <p className="text-muted-foreground mt-1">Smart Interview — AI-powered practice</p>
          </div>
          <Button variant="outline" onClick={handleLogout}>
            <LogOut className="mr-2 h-4 w-4" /> Logout
          </Button>
        </div>

        {/* Resume not uploaded yet */}
        {!hasResume && (
          <AnimatedCard delay={0.1}>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Upload className="h-5 w-5" />
                Upload Your Resume
              </CardTitle>
              <CardDescription>
                Upload your resume to get personalized technical questions generated by Groq RAG,
                spoken aloud by ElevenLabs.
              </CardDescription>
            </CardHeader>
            <CardContent>
              <Button className="w-full" onClick={() => router.push("/setup")}>
                Upload Resume &amp; Get Started
              </Button>
            </CardContent>
          </AnimatedCard>
        )}

        {/* Resume uploaded — ready to interview */}
        {hasResume && (
          <>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <AnimatedCard delay={0.1}>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-base">
                    <FileText className="h-4 w-4" /> Resume
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="text-green-600 font-semibold">Uploaded ✓</p>
                  <p className="text-xs text-muted-foreground mt-1">Chunks stored in RAG vector store</p>
                </CardContent>
              </AnimatedCard>

              <AnimatedCard delay={0.2}>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2 text-base">
                    {language === "asl" ? <Video className="h-4 w-4" /> : <Mic className="h-4 w-4" />}
                    Language
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <p className="font-semibold">{languageLabel[language] ?? language}</p>
                  <p className="text-xs text-muted-foreground mt-1">
                    <button className="underline" onClick={() => router.push("/setup")}>
                      Change
                    </button>
                  </p>
                </CardContent>
              </AnimatedCard>
            </div>

            <AnimatedCard delay={0.3}>
              <CardHeader>
                <CardTitle>Start Your Interview</CardTitle>
                <CardDescription>
                  Groq reads your resume chunks → generates 8 technical + 5 behavioral questions →
                  ElevenLabs speaks each question aloud.
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-3">
                <Button
                  size="lg"
                  className="w-full"
                  onClick={() => router.push("/interview")}
                >
                  {language === "asl"
                    ? <><Video className="mr-2 h-5 w-5" />Start Interview (ASL)</>
                    : <><Mic className="mr-2 h-5 w-5" />Start Interview</>}
                </Button>
                <Button
                  variant="outline"
                  size="lg"
                  className="w-full"
                  onClick={() => router.push("/screen")}
                >
                  <ScanSearch className="mr-2 h-5 w-5" />
                  Screen My Resume
                </Button>
                <Button
                  variant="outline"
                  className="w-full"
                  onClick={() => router.push("/setup")}
                >
                  Re-upload Resume
                </Button>
              </CardContent>
            </AnimatedCard>
          </>
        )}
      </div>
    </div>
  );
}
